# Generated by Django 5.0 on 2023-12-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unidadT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=8)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.estado')),
            ],
        ),
    ]
