# Generated by Django 5.0 on 2023-12-20 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes_appU', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carreraT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.estado')),
            ],
        ),
        migrations.CreateModel(
            name='conductorT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.PositiveIntegerField(max_length=3)),
                ('tipo_licencia', models.CharField(max_length=5)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.estado')),
            ],
        ),
        migrations.CreateModel(
            name='cursoT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.estado')),
            ],
        ),
        migrations.CreateModel(
            name='viajeT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('fk_carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.carrerat')),
                ('fk_conductor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.conductort')),
                ('fk_curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.cursot')),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.estado')),
                ('fk_unidad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='viajes_appU.unidadt')),
            ],
        ),
    ]
